'use client'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  let subdomain;
  const [host, setHost] = useState('')
  useEffect(()=> {
    setHost(window.location.host)
  })
  
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div>
        <h1>Main Domain - {host}</h1>
       </div>
      </main>

      
    </div>
  )
}
