'use client'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  let [subDomain, setSubDomain] = useState('');
  const [host, setHost] = useState('')
  // useEffect(()=> {
  //   setHost(window.location.host)
  //   const arr = host.split('.').slice(0, host.includes('localhost') ? -1 : -2)
  //   setSubDomain(arr)
  // })
  

  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div>
        <h1>Main Domain - {host}</h1>
        <h1>Sub Domain - {subDomain}</h1>
       </div>
      </main>

      
    </div>
  )
}
